BikeStore/Controllers/BrandController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BikeStoreModels;
using BikeStoreDB.DbOperations;

namespace BikeStore.Controllers
{
    public class BrandController : Controller
    {
        BrandRepository repository = null;
        public BrandController()
        {
            repository = new BrandRepository();
        }
        // GET: Brand
        public ActionResult Index()
        {
            var result = repository.GetAllBrands();
            return View(result);
        }
        public ActionResult Create()
        {            
            return View();
        }

        [HttpPost]
        public ActionResult Create(brandModel model)
        {
            if (ModelState.IsValid)
            {
                int id = repository.AddBrand(model);
                if (id > 0)
                {
                    ModelState.Clear();
                    ViewBag.Issuccess = "Data added.";
                }
            }                        
            return View();
        }

        public ActionResult Delete(brandModel model)
        {
            var br = repository.GetBrandDetails(model.brand_id);
            return View(br);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            repository.DeleteBrand(id);
            return RedirectToAction("Index");
        }

    }
}

BikeStore/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BikeStoreDB;
using BikeStoreDB.DbOperations;
using BikeStoreModels;

namespace BikeStore.Controllers
{
    [Authorize(Roles ="admin")]
    public class CategoryController : Controller
    {
        CategoryRepository repository = null;


        public CategoryController()
        {
            repository = new CategoryRepository();
        }

        // GET: Category
        public ActionResult Create()
        {         
            return View();
        }

        [HttpPost]
        public ActionResult Create(categoryModel model)
        {
            if (ModelState.IsValid)
            {
                int id = repository.CreateCategory(model);
                if (id > 0)
                {
                    ModelState.Clear();
                    ViewBag.IsSuccess = "Data added";
                }
            }
            return View();
        }

        public ActionResult AllCategory() {

            var allCategories = repository.GetAllCategories();
            return View(allCategories);
        }

        public ActionResult UpdateDetails()
        {
            return View();
        }
    }
}

BikeStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BikeStoreModels;
using BikeStoreDB.DbOperations;
using BikeStoreDB;

namespace BikeStore.Controllers
{
    [RoutePrefix("product")]
    public class ProductController : Controller
    {
        ProductRepository repository = null;
        public ProductController()
        {
            repository = new ProductRepository();
        }
       
        public ActionResult AllProducts()
        {
            var result = repository.GetAllProducts();
            return View(result);
        }

  
        public ActionResult ProductDetails(int id)
        {
            var result = repository.GetProductDetails(id);
            return View(result);
        }
       
     
        // GET: Product
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            BikeStores_2Entities db = new BikeStores_2Entities();
            List<categoryModel> cat = db.categories.Select(x => new categoryModel
            {
                category_id = x.category_id,
                category_name = x.category_name
            }).ToList();

            List<brandModel> brands = db.brands.Select(x => new brandModel
            {
                brand_id = x.brand_id,
                brand_name = x.brand_name
            }).ToList();

            ViewBag.CategoryList = new SelectList(cat, "category_id", "category_name");
            ViewBag.BrandList = new SelectList(brands, "brand_id", "brand_name");

            return View();
        }

        //POST: Product
        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Create(productModel model)
        {
            BikeStores_2Entities db = new BikeStores_2Entities();
            List<categoryModel> cat = db.categories.Select(x => new categoryModel
            {
                category_id = x.category_id,
                category_name = x.category_name
            }).ToList();

            List<brandModel> brands = db.brands.Select(x => new brandModel
            {
                brand_id = x.brand_id,
                brand_name = x.brand_name
            }).ToList();

            ViewBag.CategoryList = new SelectList(cat, "category_id", "category_name");
            ViewBag.BrandList = new SelectList(brands, "brand_id", "brand_name");

            if (ModelState.IsValid)
            {
                int id = repository.AddProduct(model);
                if (id > 0)
                {
                    ModelState.Clear();
                    ViewBag.Issuccess = "Data added.";
                }
            }
            return View();
        }

        
        
        public ActionResult Edit(int id)
        {
            var prod = repository.GetProductDetails(id);
            return View(prod);
        }
        [HttpPost]
        public ActionResult Edit(productModel model)
        {
            if (ModelState.IsValid)
            {
                repository.UpdateProductDetails(model.product_id, model);
                return RedirectToAction("AllProducts");
            }

            return View();
        }
       
        public ActionResult Delete(productModel model)
        {
            var prod = repository.GetProductDetails(model.product_id);
            return View(prod);
        }
       
        [HttpPost]
        public ActionResult Delete(int id)
        {           
                repository.DeleteProduct(id);
                return RedirectToAction("AllProducts");           
        }

    }
}

BikeStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BikeStoreDB;
using BikeStoreDB.DbOperations;
using BikeStoreModels;

namespace BikeStore.Controllers
{
    public class StoreController : Controller
    {
        // GET: Store
        StoreRepository repository = null;
        public StoreController()
        {
            repository = new StoreRepository();
        }
        public ActionResult Index()
        {
            var result = repository.GetAllStores();
            return View(result);
        }


        public ActionResult Details(int id)
        {
            var result = repository.GetStoreDetails(id);
            return View(result);
        }

        // GET: Product
        public ActionResult Create()
        {               
            return View();
        }

        //POST: Product
        [HttpPost]
        public ActionResult Create(storeModel model)
        {

            BikeStores_2Entities db = new BikeStores_2Entities();
   
            if (ModelState.IsValid)
            {
                int id = repository.AddStore(model);
                if (id > 0)
                {
                    ModelState.Clear();
                    ViewBag.Issuccess = "Data added.";
                }
            }
            return View();
        }


        public ActionResult Edit(int id)
        {
            var st = repository.GetStoreDetails(id);
            return View(st);
        }
        [HttpPost]
        public ActionResult Edit(storeModel model)
        {
            if (ModelState.IsValid)
            {
                repository.UpdateStoreDetails(model.store_id, model);
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Delete(storeModel model)
        {
            var st = repository.GetStoreDetails(model.store_id);
            return View(st);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            repository.DeleteStore(id);
            return RedirectToAction("Index");
        }
    }
}

BikeStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="~/Scripts/jquery-3.7.0.min.js"></script>
    <link href="~/CustomCSS/layoutSS.css" rel="stylesheet" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />


    <link href="~/Content/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/dataTables.bootstrap.min.css" rel="stylesheet" />
    <title>bikestore.com</title>

    <style>
        #navbarNavDarkDropdown .navbar-nav .fa {
            padding: 12px 0px 0px 21px;
        }
        dropdownMenuButton {
            transition: max-height 0.3s ease-in-out, opacity 0.3s ease-in-out;
            max-height: 0;
            overflow: hidden;
        }

        .show .dropdown-menu {
            max-height: 500px; /* Adjust the value to your preference */
            opacity: 1;
        }
        .cls6565 {
            color: #ff6565;
            font-size: 22px;
            text-decoration:none;
        }

        .nav-item {
            margin-right: 13px;
        }
        .nav-link {
            border-bottom: 3px solid #212529;
            
        }
        .active {
            border-bottom: 3px solid #ff6565;
        }
        .nav-link:hover {
            border-bottom: 3px solid #ffaaaa;
        }
    </style>

</head>
<body style="font-family:Verdana">
    <header>
        <nav class="navbar navbar-expand-lg " style="background-color: #212529">
            <div class="container-fluid ">

                <a class="cls6565  " style="" href="/Home/Home"><b>BIKE STORE</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                    <i class="fa-solid fa-bars fa-lg" style="color: #ff6565;"></i>
                </button>

                <div class="offcanvas offcanvas-end" id="offcanvasNavbar" tabindex="-1" labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header ">

                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body bg-dark" id="navbarNavDarkDropdown">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">

                            <li class="nav-item">
                                <i class="fa fa-home fa-lg" style="color:white"></i>
                                @Html.ActionLink("Home", "Home", "Home", null, new { id = "menuHome", style = "color:white;", @class = "nav-link d-inline", aria_current = "page" })
                            </li>
                            <li class="nav-item">
                                <i class="fa fa-address-book fa-lg" style="color:white"></i>
                                @Html.ActionLink("About", "About", "Home", null, new { onclick = "toggleMenu(this)", id = "menuAbout", style = "color:white;", @class = "nav-link d-inline", aria_current = "page" })
                            </li>


                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("admin"))
                                {
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle " style="color:white;" role="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                            Manage
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton" id="ddmenu">

                                            <li>
                                                @Html.ActionLink("Products", "AllProducts", "Product", null, new { @class = "dropdown-item" })
                                            </li>
                                            <li>
                                                @Html.ActionLink("Brands", "Index", "Brand", null, new { @class = "dropdown-item" })
                                            </li>
                                            <li>
                                                @Html.ActionLink("Categories", "AllCategory", "Category", null, new { @class = "dropdown-item" })
                                            </li>
                                            <li>
                                                @Html.ActionLink("Stock", "Index", "Stock", null, new { @class = "dropdown-item" })
                                            </li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li>
                                                @Html.ActionLink("Staff", "Index", "Staff", null, new { @class = "dropdown-item" })
                                            </li>
                                            <li>
                                                @Html.ActionLink("Stores", "Index", "Store", null, new { @class = "dropdown-item" })
                                            </li>
                                            <li>
                                                @Html.ActionLink("Customers", "Index", "Customers", null, new { @class = "dropdown-item" })
                                            </li>
                                        </ul>
                                    </li>
                                }

                        <li>
                            @*<a id="menuProfile" style="color:white;" class="nav-link" href="/Customer/CustomerProfile"></a>*@
                            <i class="fa-solid fa-user " style="color: #ffffff;"></i>
                            @Html.ActionLink("User", "CustomerProfile", "Customer", new { email = User.Identity.Name }, new { style = "color:white; display:inline-block", @class = "  nav-link", id = "menuProfile" })
                            <input type="hidden" value="@User.Identity.Name" id="cemail" />
                        </li>

                                <li>
                                    @Html.ActionLink("Logout", "#", null, new { style = "color:white;", data_toggle = "modal", data_target = "#messageModal", @class = "nav-link" })
                                </li>

                            }
                            else
                            {
                                <i class="fa fa-user fa-lg" style="color:white"></i>
                                <li class="nav-item" )>
                                    @Html.ActionLink("Login", "Login", "Customer", null, new { id = "menuLogin", style = "color:white;", @class = "nav-link " })
                                </li>
                                @*<li class="" )>
                                        @Html.ActionLink("Signup", "Create", "Customer", null, new { @class = "nav-link active", aria_current = "page" })
                                    </li>*@
                            }
                        </ul>
                        @using (Html.BeginForm("Home", "Home", FormMethod.Get, new { @class = "d-flex", role = "search" }))
                        {
                            @Html.TextBox("search", null, new { placeholder = "Search", @class = "form-control  me-2" })
                            <button class="btn btn-success" style="background-color: #ff6565; border:none" type="submit">Search</button>
                        }
                    </div>

                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid body-content " style="margin-top:-10px; padding-left: 0px; padding-right: 0px;">
        @RenderBody()
        <hr />

        <footer>
            <p>&copy; @DateTime.Now.Year -My Bike Store</p>
        </footer>
    </div>

    <div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-body">
                    <!-- Your message content here -->
                    Do you really want to logout?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn " style="background-color: #212529; color:white " data-dismiss="modal">No</button>
                    @Html.ActionLink("Yes", "Logout", "Customer", null, new { id = "log_out", @class = "btn", style = "background-color: #ff6565" })
                </div>
            </div>
        </div>
    </div>

    @if (User.Identity.IsAuthenticated)
    {
        <script>
            $(document).ready(function () {
                var em = $("#cemail").val();    
                $.ajax({
                    url: "/Customer/GetCustomerName",
                    method: "GET",
                    data: { email: em },
                    success: function (data) {                     
                        var anchorTag = document.getElementById("menuProfile");
                        anchorTag.textContent = data;
                    },
                    error: function () {
                        var anchorTag = document.getElementById("menuProfile");
                        anchorTag.textContent = "Hello User";
                    }
                })
            })
        </script>

    }
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>

    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap.min.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#tbllist').DataTable({

            });
        });




        $(document).ready(function () {
            // Get the current URL path
            var path = window.location.pathname;

            // Add 'active' class to the corresponding menu item
            if (path === "/") {
                $("#menuHome").addClass("active");
            } else if (path === "/Home/About") {
                $("#menuAbout").addClass("active");
            } else if (path === "/Customer/Login") {
                $("#menuLogin").addClass("active");
            } else if (path === "/Customer/CustomerProfile") {
                $("#menuProfile").addClass("active");
            }

        });

        function toggleMenu(a) {
            a.addClass("active");
        }
    </script>
</body>
</html>